import {readFile,writeFile,mkdir,rename} from 'node:fs/promises';
import {join} from 'node:path';
import {createHash,randomUUID} from 'node:crypto';
import {uploadType} from './upload-categories.mjs';
import {onboardingSteps} from './onboarding.mjs';
export function agentStore(root,loadFirms){let queue=Promise.resolve();const base=join(root,'data','agent');
  async function scope(firmId,period){if(!/^[a-zA-Z0-9-]{1,80}$/.test(firmId)||!/^\d{4}-(0[1-9]|1[0-2])$/.test(period))throw Error('Firma veya dönem geçersiz.');if(!(await loadFirms()).some(f=>f.id===firmId))throw Error('Önce kayıtlı bir firma seç.');return join(base,firmId,period);}
  async function read(firmId,period){const dir=await scope(firmId,period);try{return JSON.parse(await readFile(join(dir,'workspace.json'),'utf8'));}catch(e){if(e.code==='ENOENT')return {revision:0,docs:[],rules:[],history:[],messages:[],instruction:''};throw e;}}
  function mutate(firmId,period,fn){const op=queue.then(async()=>{const dir=await scope(firmId,period),data=await read(firmId,period);const result=await fn(data,dir);data.revision++;await mkdir(dir,{recursive:true});await writeFile(join(dir,'workspace.tmp'),JSON.stringify(data));await rename(join(dir,'workspace.tmp'),join(dir,'workspace.json'));return {result,workspace:data};});queue=op.catch(()=>{});return op;}
  return {read,upload:async(firmId,period,name,bytes,category='expense')=>{const type=uploadType(category);const ext=String(name).split('.').pop().toLowerCase();if(!['pdf','png','jpg','jpeg','xml'].includes(ext)||!bytes.length||bytes.length>20*1024*1024)throw Error('PDF, JPG, PNG veya XML; en fazla 20 MB.');const hash=createHash('sha256').update(bytes).digest('hex');return mutate(firmId,period,async(data,dir)=>{const existing=data.docs.find(d=>d.hash===hash);if(existing)return {document:existing,duplicate:true};const id=randomUUID();await mkdir(dir,{recursive:true});await writeFile(join(dir,id+'.bin'),bytes);const doc={id,name:String(name).slice(0,200),hash,size:bytes.length,uploadedAt:new Date().toISOString(),vendor:'',type,uploadCategory:category,amount:null,account:'',status:'waiting',demo:false,documentDate:'',documentNumber:'',note:'Belge arşivlendi. Tür, tarih, numara, tutar ve hesap bilgilerini kontrol et.',url:`/api/archive/file?firmId=${encodeURIComponent(firmId)}&period=${period}&id=${id}`};data.docs.push(doc);return {document:doc,duplicate:false};});},
  save:(firmId,period,input)=>mutate(firmId,period,data=>{if(input.revision!==data.revision)throw Error('Kayıt başka bir işlemle değişti. Sayfayı yenilemeden önce değişikliklerini not al.');if(!Array.isArray(input.docs)||!Array.isArray(input.rules)||!Array.isArray(input.messages)||!Array.isArray(input.history))throw Error('Çalışma alanı geçersiz.');for(const doc of data.docs){const edit=input.docs.find(d=>d.id===doc.id);if(!edit)continue;for(const key of ['vendor','type','account','documentDate','documentNumber','payment','taxNotes'])doc[key]=String(edit[key]||'').slice(0,500);for(const field of ['amount','netAmount','vatAmount']){doc[field]=edit[field]==null||edit[field]===''?null:Number(edit[field]);if(doc[field]!==null&&(!Number.isFinite(doc[field])||doc[field]<0||(field==='amount'&&doc[field]===0)))throw Error('Belge tutarı geçersiz.');}doc.status=edit.status==='ready'?'ready':'waiting';}data.rules=input.rules.slice(0,1000).map(r=>({name:String(r.name||'').slice(0,500),code:String(r.code||'').slice(0,100)}));data.instruction=String(input.instruction||'').slice(0,20000);data.messages=input.messages.slice(-200).map(m=>({text:String(m.text||'').slice(0,20000),user:m.user===true}));data.history=input.history.slice(0,1000).map(h=>({time:String(h.time||''),message:String(h.message||'').slice(0,2000)}));return true;}),
  file:async(firmId,period,id)=>{const data=await read(firmId,period),doc=data.docs.find(d=>d.id===id);if(!doc)throw Error('Belge bulunamadı.');return {doc,bytes:await readFile(join(await scope(firmId,period),doc.id+'.bin'))};}
  };
}
export function prepareManifest(firm,profile,workspace,period){const issues=onboardingSteps(firm).map(s=>'Başlangıç görevi bekliyor: '+s.title);if(!profile)issues.push('Aylık görev ayarları yok.');if(!profile?.lucaFirmCode)issues.push('LUCA firma kodu eşleştirilmedi.');if(!firm.email)issues.push('Firma e-posta adresi eksik.');if(profile?.hasSgk==='yes')issues.push('Bu dönemin bordro, prim günü, eksik gün ve kazanç bilgileri doğrulanmalı.');if(profile?.landlords?.length)issues.push('Bu dönemin fiilî kira ödemeleri ve stopaj bilgileri doğrulanmalı.');const seen=new Set();const documents=workspace.docs.map(d=>{const missing=[];for(const [key,label] of [['vendor','Cari'],['account','Hesap'],['documentDate','Belge tarihi'],['documentNumber','Belge numarası'],['payment','Ödeme/cari kapatma yöntemi']])if(!d[key])missing.push(label);if(!d.amount||d.amount<=0)missing.push('Tutar');if(d.documentDate&&!d.documentDate.startsWith(period+'-'))missing.push('Belge tarihi dönem dışında');if(d.netAmount==null||d.vatAmount==null)missing.push('Matrah/KDV tutarı');else if(Math.round(d.netAmount*100)+Math.round(d.vatAmount*100)!==Math.round(d.amount*100))missing.push('Matrah + KDV toplamı uyuşmuyor; kesinti/tevkifat ve diğer kalemler incelenmeli');if(d.taxNotes)missing.push('Vergi notları: '+d.taxNotes);if(d.status!=='ready')missing.push('Belge kontrolü');if(d.documentNumber&&d.vendor){const businessKey=(d.vendor+'|'+d.documentNumber+'|'+d.documentDate).toLocaleUpperCase('tr').replace(/\s+/g,'');if(seen.has(businessKey))missing.push('Aynı cari/tarih/belge numarası tekrar ediyor');seen.add(businessKey);}return {id:d.id,name:d.name,hash:d.hash,type:d.type,amount:d.amount,missing};});for(const d of documents)if(d.missing.length)issues.push(`${d.name}: ${d.missing.join(', ')}`);if(!documents.length)issues.push('Yerel arşivde belge yok; LUCA kaynakları henüz sorgulanmadı.');issues.push('Chrome/LUCA bağlantısı bekleniyor.');const core={onboarding:{firmType:firm.firmType||'unknown',updatedAt:firm.onboardingUpdatedAt||null,ismmmoContractNumber:firm.ismmmoContractNumber||''},firmId:firm.id,firmName:firm.name,email:firm.email||'',period,workspaceRevision:workspace.revision,profileUpdatedAt:profile?.updatedAt||null,instruction:workspace.instruction,documents,issues};return {...core,hash:createHash('sha256').update(JSON.stringify(core)).digest('hex'),generatedAt:new Date().toISOString(),kind:'preparation_manifest',canSubmit:false};}
